services:
  web:
    build:
      context: .
      target: builder
    ports:
      - 4201:4201
    volumes:
      - ./ndakisa:/project
      - /project/node_modules 
  

networks:
  app-network:
    driver: bridge