version: '3'

services:
  ndakisa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ndakisa
    image: ndakisa
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - 4200:80

volumes:
  angularngixvolume:

# docker system prune
# docker rmi -f ndakisa-api  // Supprimer une image
# docker compose build ndakisa
# docker compose up --build -d ndakisa 

# https://github.com/kprasad99/angular-nginx-docker   // Reference
